### PR TITLE
fix issue with new npm

### PR DESCRIPTION
**Pull request by jimmy927**

### CODE REVIEW

**Comment by EPMatt** [comment]
Hi @jimmy927,
I'm closing this as duplicate of #36.

Anyway, thank you so much for your contribution! 🚀

**Comment by jimmy927** [comment]
> Hi @jimmy927, I'm closing this as duplicate of #36.

Not really.
You should really use npx like in my solution, see npm documentation.

**Comment by EPMatt** [comment]
Hi @jimmy927,
thank you for your quick response.

> use npx like in my solution, see npm documentation.

Could you please elaborate a little more on this and provide a link to the docs?

The other user provided a valid solution without the use of `npx`, which proved to work correctly in the PR tests. Are you aware of any case that solution might not work as expected?

Thanks!

**Comment by jimmy927** [comment]
> Could you please elaborate a little more on this and provide a link to the docs?

https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/

> npm bin has been removed (use npx or npm exec to execute binaries)

**Pull request closed without merging**
